service: serverless-pdf

provider:
  name: aws
  runtime: nodejs4.3
  stage: stage
  region: us-west-2
  profile: serverless

functions:
  print:
    timeout: 15
    handler: handler.print
    events:
      - http:
          method: post
          path: print
          cors: true

plugins:
  - serverless-webpack
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - bin/phantomjs-macosx
  include:
    - phantom-renderscript.js
    - bin/phantomjs-linux
