service:                  serverless-pdf

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules:  true
  serverless-offline:
    babelOptions:
      presets:            ["es2015", "stage-3"]

provider:
  name:                   aws
  runtime:                nodejs6.10
  stage:                  prod
  region:                 eu-west-1
  profile:                serverless

functions:
  print:
    timeout:              15
    handler:              handler.print
    events:
      - http:
          method:         post
          path:           print
          cors:           true

  printToBucket:
    environment:          ${file(env.yml):${opt:stage}}
    timeout:              15
    handler:              handler.printToBucket
    events:
      - http:
          method:         post
          path:           printToBucket
          cors:           true

  getFromBucket:
    environment:          ${file(env.yml):${opt:stage}}
    handler:              handler.getFromBucket
    events:
      - http:
          method:         get
          path:           getFromBucket
          cors:           true
          request:
          parameters:
            querystrings:
              id:         true
