service:                    serverless-pdf

provider:
  name:                     aws
  runtime:                  nodejs6.10
  stage:                    stage
  region:                   us-west-2
  profile:                  serverless

functions:
  print:
    timeout:                15
    handler:                handler.print
    events:
      - http:
          method:           post
          path:             print
          cors:             true

  printToBucket:
    environment:            ${file(env.yml)}
    timeout:                15
    handler:                handler.printToBucket
    events:
      - http:
          method:           post
          path:             printToBucket
          cors:             true

    getFromBucket:
      environment:          ${file(env.yml)}
      handler:              handler.getFromBucket
      events:
        - http:
            method:         get
            path:           getFromBucket
            cors:           true
            request:
            parameters:
              querystrings:
                id:         true

custom:
  webpackIncludeModules: true

plugins:
  - serverless-webpack
  - serverless-offline
